name: Deploy VisIacap Frontend

on:
  push:
    branches:
      - main  # Esto hace que se dispare solo cuando haces push a la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout código
        uses: actions/checkout@v4

      - name: 🏗️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependencias
        run: npm install

      - name: 🛠️ Generar Build de Producción
        run: npx ionic build --prod

      - name: 🚀 Subir archivos a V2Network (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./www/
          server-dir: /inacapsmart.cl/
          state-name: .ftp-deploy-sync-state.json # Esto ayuda a que solo suba los cambios nuevos